---

on:
  push:
    branches:
      - master

name: Workflow for development branch
jobs:
  build:
    runs-on: macos-10.15
    env:
      ROOTDIR: ${{ github.workspace }}/usr
    steps:
      - uses: actions/checkout@master
      - uses: vmactions/freebsd-vm@v0.1.3
        with:
          prepare: pkg install poudriere-devel
          usesh: true
          run: |
            poudriere ports -c -p default -m null -M /usr/ports
            poudriere ports -c -U ${{ github.repository }} -p sensless-ports -m git -B ${GITHUB_REF##*/}
            poudriere jail -c -j 13-0-amd64 -v stable/13 -a amd64 -m git
            poudriere bulk  -j 13-0-amd64 -O sensless-ports devel/phpunit7
