---

on:
  push:
    branches:
      - main

name: Workflow for development branch
jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 1200
    env:
      FREEBSD_MAJOR_VERSION: 12
      FREEBSD_MINOR_VERSION: 3
    steps:
      - uses: actions/checkout@master
      - uses: os-runners/freebsd-vm@main
        with:
          prepare: pkg install -y git-lite poudriere-devel
          version: 13.0
          auto_update: true
          memory: 10240
          usesh: true
          run: |
            mkdir -p /usr/ports/distfiles
            mv poudriere.conf /usr/local/etc/poudriere.conf
            poudriere ports -c -U https://github.com/${{ github.repository }}.git -p senseless -B ${GITHUB_REF##*/}
            poudriere jail -c -j ${{ env.FREEBSD_MAJOR_VERSION }}-${{ env.FREEBSD_MINOR_VERSION }}-amd64 -v stable/${{ env.FREEBSD_MAJOR_VERSION }} -m git+https
            poudriere bulk -j ${{ env.FREEBSD_MAJOR_VERSION }}-${{ env.FREEBSD_MINOR_VERSION }}-amd64 -O senseless -b latest -f pkglist
