---

on:
  push:
    branches:
      - main

name: Workflow for development branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build custom FreeBSD ports overlay
        uses: vmactions/freebsd-vm@v1.2.3
        with:
          prepare: |
            pkg install -y git-lite poudriere-devel
          usesh: true
          run: |
            mkdir -p /usr/ports/distfiles
            mv poudriere.conf /usr/local/etc/poudriere.conf
            poudriere jail -c -j 14_3_release -m ftp -v 14.3-RELEASE
            poudriere ports -c -U https://github.com/${{ github.repository }}.git -p senseless -B ${GITHUB_REF##*/}
            poudriere bulk -j 14_3_release -O senseless -b latest -f portlist.txt -p senseless
