---

on:
  push:
    branches:
      - main

name: Workflow for development branch
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Build custom FreeBSD ports overlay
        uses: vmactions/freebsd-vm@v0
        with:
          prepare: pkg install -y git-lite poudriere-devel
          release: 13.1
          auto_update: true
          memory: 10240
          usesh: true
          run: |
            mkdir -p /usr/ports/distfiles
            mv poudriere.conf /usr/local/etc/poudriere.conf
            poudriere ports -c -U https://github.com/${{ github.repository }}.git -p senseless -B ${GITHUB_REF##*/}
            poudriere bulk -O senseless -b latest -f pkglist 
